<a href="https://colab.research.google.com/github/rithz623/Practice-projects/blob/main/Titanic_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
trainData = pd.read_csv('/content/drive/MyDrive/MLClass2024/train.csv')
testData = pd.read_csv('/content/drive/MyDrive/MLClass2024/test.csv')
ansData = pd.read_csv('/content/drive/MyDrive/MLClass2024/gender_submission.csv')
trainData.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
testData.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [ ]:
trainData.drop("Name", axis=1, inplace=True)
testData.drop("Name", axis=1, inplace=True)
trainData.drop("Cabin", axis=1, inplace=True)
testData.drop("Cabin", axis=1, inplace=True)
trainData.drop("Ticket", axis=1, inplace=True)
testData.drop("Ticket", axis=1, inplace=True)

In [ ]:
trainData

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
888          889         0       3  female   NaN      1      2  23.4500   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked  
0          S  
1          C  
2          S  
3          S  
4          S  
..       ...  
886        S  
887        S  
888        S  
889        C  
890        Q  

[891 rows x 9 columns]

In [ ]:
encoder = {"Sex": {"male": 0, "female": 1}, "Embarked": {"S": 0, "C": 1, "Q": 2}}
trainData.replace(encoder, inplace=True)
testData.replace(encoder, inplace=True)

<ipython-input-9-7c197980d1ad>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  trainData.replace(encoder, inplace=True)
<ipython-input-9-7c197980d1ad>:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  testData.replace(encoder, inplace=True)


In [ ]:
trainData

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0              1         0       3    0  22.0      1      0   7.2500       0.0
1              2         1       1    1  38.0      1      0  71.2833       1.0
2              3         1       3    1  26.0      0      0   7.9250       0.0
3              4         1       1    1  35.0      1      0  53.1000       0.0
4              5         0       3    0  35.0      0      0   8.0500       0.0
..           ...       ...     ...  ...   ...    ...    ...      ...       ...
886          887         0       2    0  27.0      0      0  13.0000       0.0
887          888         1       1    1  19.0      0      0  30.0000       0.0
888          889         0       3    1   NaN      1      2  23.4500       0.0
889          890         1       1    0  26.0      0      0  30.0000       1.0
890          891         0       3    0  32.0      0      0   7.7500       2.0

[891 rows x 9 columns]

In [ ]:
testData

PassengerId  Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0            892       3    0  34.5      0      0    7.8292         2
1            893       3    1  47.0      1      0    7.0000         0
2            894       2    0  62.0      0      0    9.6875         2
3            895       3    0  27.0      0      0    8.6625         0
4            896       3    1  22.0      1      1   12.2875         0
..           ...     ...  ...   ...    ...    ...       ...       ...
413         1305       3    0   NaN      0      0    8.0500         0
414         1306       1    1  39.0      0      0  108.9000         1
415         1307       3    0  38.5      0      0    7.2500         0
416         1308       3    0   NaN      0      0    8.0500         0
417         1309       3    0   NaN      1      1   22.3583         1

[418 rows x 8 columns]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X = trainData.drop("Survived", axis=1)
y = trainData["Survived"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((712, 8), (179, 8), (712,), (179,))

In [ ]:
ansData

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
trainedData = RandomForestClassifier()
trainedData.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
yPredictions = trainedData.predict(X_test)
yPredictions[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [ ]:
trainedData.score(X_test, y_test)

0.8491620111731844

In [ ]:
randomSearchParams = {"n_estimators": [10, 50, 100, 500, 1000],
                      "n_jobs": [2, 5, 10, 50, 100],
                      "min_samples_leaf": [1, 2, 5, 10, 50],
                      "max_features": [1, 2, 5, 10, 50],
                      "max_depth": [1, 2, 5, 10, 50]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
randomSearchModel = RandomForestClassifier(n_jobs=-1)
rs_randomSearchModel = RandomizedSearchCV(estimator = RandomForestClassifier(n_jobs=-1),
                                          param_distributions = randomSearchParams,
                                          n_iter = 30,
                                          cv = 5,
                                          verbose = 2)


In [ ]:
rs_randomSearchModel.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END max_depth=1, max_features=1, min_samples_leaf=1, n_estimators=50, n_jobs=5; total time=   0.2s
[CV] END max_depth=1, max_features=1, min_samples_leaf=1, n_estimators=50, n_jobs=5; total time=   0.2s
[CV] END max_depth=1, max_features=1, min_samples_leaf=1, n_estimators=50, n_jobs=5; total time=   0.2s
[CV] END max_depth=1, max_features=1, min_samples_leaf=1, n_estimators=50, n_jobs=5; total time=   0.2s
[CV] END max_depth=1, max_features=1, min_samples_leaf=1, n_estimators=50, n_jobs=5; total time=   0.2s
[CV] END max_depth=50, max_features=10, min_samples_leaf=50, n_estimators=50, n_jobs=50; total time=   0.2s
[CV] END max_depth=50, max_features=10, min_samples_leaf=50, n_estimators=50, n_jobs=50; total time=   0.2s
[CV] END max_depth=50, max_features=10, min_samples_leaf=50, n_estimators=50, n_jobs=50; total time=   0.2s
[CV] END max_depth=50, max_features=10, min_samples_leaf=50, n_estimators=50, n_jobs=50; total

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1), n_iter=30,
                   param_distributions={'max_depth': [1, 2, 5, 10, 50],
                                        'max_features': [1, 2, 5, 10, 50],
                                        'min_samples_leaf': [1, 2, 5, 10, 50],
                                        'n_estimators': [10, 50, 100, 500,
                                                         1000],
                                        'n_jobs': [2, 5, 10, 50, 100]},
                   verbose=2)

In [ ]:
rs_randomSearchModel.best_params_

{'n_jobs': 10,
 'n_estimators': 1000,
 'min_samples_leaf': 2,
 'max_features': 5,
 'max_depth': 5}

In [ ]:
randomYPredictions = rs_randomSearchModel.predict(X_test)
randomYPredictions[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
randomSearchScore = rs_randomSearchModel.score(X_test, y_test)
randomSearchScore

0.8491620111731844

In [ ]:
gridSearchParams = {'n_jobs': [10],
                    'n_estimators': [1000],
                    'min_samples_leaf': [2],
                    'max_features': [5],
                    'max_depth': [5],
                    'max_leaf_nodes': [1, 5, 10, 25, 50],
                    'min_samples_split': [2, 5, 10, 50, 100],
                    'max_samples': [1, 2, 5, 10, 50]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
gridSearchModel = RandomForestClassifier(n_jobs=-1)
grid_SearchModel = RandomizedSearchCV(estimator = RandomForestClassifier(n_jobs=-1),
                                          param_distributions = gridSearchParams,
                                          n_iter = 30,
                                          cv = 5,
                                          verbose = 2)

In [ ]:
grid_SearchModel.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=10, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.5s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=10, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.7s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=10, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.9s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=10, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.6s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=10, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.6s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=5, max_samples=1, min_samples_leaf=2, min_samples_split=50, n_estimators=10

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
40 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
40 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1), n_iter=30,
                   param_distributions={'max_depth': [5], 'max_features': [5],
                                        'max_leaf_nodes': [1, 5, 10, 25, 50],
                                        'max_samples': [1, 2, 5, 10, 50],
                                        'min_samples_leaf': [2],
                                        'min_samples_split': [2, 5, 10, 50,
                                                              100],
                                        'n_estimators': [1000],
                                        'n_jobs': [10]},
                   verbose=2)

In [ ]:
grid_SearchModel.best_params_

{'n_jobs': 10,
 'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_samples': 50,
 'max_leaf_nodes': 5,
 'max_features': 5,
 'max_depth': 5}

In [ ]:
grid_SearchModel.best_params_

{'n_jobs': 10,
 'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_samples': 50,
 'max_leaf_nodes': 5,
 'max_features': 5,
 'max_depth': 5}

In [ ]:
gridYPredictions = grid_SearchModel.predict(X_test)
gridYPredictions[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
gridSearchScore = grid_SearchModel.score(X_test, y_test)
gridSearchScore

0.7877094972067039

In [ ]:
gridParams = {'min_samples_split': [1, 5, 10, 50, 100],
                    'min_samples_leaf': [1, 5, 10, 50, 100],
                    'min_samples_leaf': [1, 5, 10, 50, 100],
                    'min_weight_fraction_leaf': [1, 5, 10, 50, 100],
                    'max_features': ['sqrt'],
                    'max_leaf_nodes' : [1, 5, 10, 50, 100],
                    'min_impurity_decrease' : [1, 5, 10, 50, 100],
                    'warm_start' : [True ,False],
                    "class_weight" : ['balanced', 'balanced_subsample'],
                    'max_samples' : [1, 5, 10, 50, 100],
                    'max_samples' : [1, 5, 10, 50, 100],
                    'max_depth' : [1, 5, 10, 50, 100],
                    'n_estimators' : [1, 5, 10, 100, 1000]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
grid1SearchModel = RandomForestClassifier(n_jobs=-1)
grid1_SearchModel = RandomizedSearchCV(estimator = RandomForestClassifier(n_jobs=-1),
                                          param_distributions = gridSearchParams,
                                          n_iter = 30,
                                          cv = 5,
                                          verbose = 2)

In [ ]:
grid1_SearchModel.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=50, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   3.4s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=50, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   3.0s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=50, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.5s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=50, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   2.5s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=50, min_samples_leaf=2, min_samples_split=2, n_estimators=1000, n_jobs=10; total time=   3.0s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=10, max_samples=5, min_samples_leaf=2, min_samples_split=10, n_estimat

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
30 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1), n_iter=30,
                   param_distributions={'max_depth': [5], 'max_features': [5],
                                        'max_leaf_nodes': [1, 5, 10, 25, 50],
                                        'max_samples': [1, 2, 5, 10, 50],
                                        'min_samples_leaf': [2],
                                        'min_samples_split': [2, 5, 10, 50,
                                                              100],
                                        'n_estimators': [1000],
                                        'n_jobs': [10]},
                   verbose=2)

In [ ]:
grid1_SearchModel.best_params_

{'n_jobs': 10,
 'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_samples': 50,
 'max_leaf_nodes': 25,
 'max_features': 5,
 'max_depth': 5}

In [ ]:
grid1YPredictions = grid_SearchModel.predict(X_test)
grid1YPredictions[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
grid1SearchScore = grid_SearchModel.score(X_test, y_test)
grid1SearchScore

0.7877094972067039

In [ ]:
randomParams = {'min_samples_split': [1, 5, 10, 50, 100],
                    'min_samples_leaf': [1, 5, 10, 50, 100],
                    'min_samples_leaf': [1, 5, 10, 50, 100],
                    'min_weight_fraction_leaf': [1, 5, 10, 50, 100],
                    'max_features': ['sqrt'],
                    'max_leaf_nodes' : [1, 5, 10, 50, 100],
                    'min_impurity_decrease' : [1, 5, 10, 50, 100],
                    'warm_start' : [True ,False],
                    "class_weight" : ['balanced', 'balanced_subsample'],
                    'max_samples' : [1, 5, 10, 50, 100],
                    'max_samples' : [1, 5, 10, 50, 100],
                    'max_depth' : [1, 5, 10, 50, 100],
                    'n_estimators' : [1, 5, 10, 100, 1000]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
random1SearchModel = RandomForestClassifier(n_jobs=-1)
random1_SearchModel = RandomizedSearchCV(estimator = RandomForestClassifier(n_jobs=-1),
                                          param_distributions = gridSearchParams,
                                          n_iter = 30,
                                          cv = 5,
                                          verbose = 2)

In [ ]:
random1_SearchModel.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=1, min_samples_leaf=2, min_samples_split=5, n_estimators=1000, n_jobs=10; total time=   3.8s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=1, min_samples_leaf=2, min_samples_split=5, n_estimators=1000, n_jobs=10; total time=   3.0s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=1, min_samples_leaf=2, min_samples_split=5, n_estimators=1000, n_jobs=10; total time=   3.9s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=1, min_samples_leaf=2, min_samples_split=5, n_estimators=1000, n_jobs=10; total time=   3.4s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=25, max_samples=1, min_samples_leaf=2, min_samples_split=5, n_estimators=1000, n_jobs=10; total time=   2.5s
[CV] END max_depth=5, max_features=5, max_leaf_nodes=50, max_samples=2, min_samples_leaf=2, min_samples_split=10, n_estimators=1

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
25 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(n_jobs=-1), n_iter=30,
                   param_distributions={'max_depth': [5], 'max_features': [5],
                                        'max_leaf_nodes': [1, 5, 10, 25, 50],
                                        'max_samples': [1, 2, 5, 10, 50],
                                        'min_samples_leaf': [2],
                                        'min_samples_split': [2, 5, 10, 50,
                                                              100],
                                        'n_estimators': [1000],
                                        'n_jobs': [10]},
                   verbose=2)

In [ ]:
random1_SearchModel.best_params_

{'n_jobs': 10,
 'n_estimators': 1000,
 'min_samples_split': 5,
 'min_samples_leaf': 2,
 'max_samples': 50,
 'max_leaf_nodes': 25,
 'max_features': 5,
 'max_depth': 5}

In [ ]:
random1YPredictions = grid_SearchModel.predict(X_test)
random1YPredictions[:10]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
random1SearchScore = grid_SearchModel.score(X_test, y_test)
random1SearchScore

0.7877094972067039